version: '3'

services:
  ipfs_host:
    image: ipfs/go-ipfs:latest
    environment:
      IPFS_PROFILE: server
    ports:
      - "80:80"
      - "4001:4001"
      - "4001:4001/udp"
      - "8083:8080"
      - "5001:5001"
